"""add ai settings to global config

Revision ID: 5a2431f8df98
Revises: d5c05fd7a995
Create Date: 2026-03-10 10:50:21.991196

"""

from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a2431f8df98"
down_revision: str | None = "d5c05fd7a995"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("global_config", sa.Column("temperature", sa.Integer(), nullable=True))
    op.add_column("global_config", sa.Column("top_p", sa.Integer(), nullable=True))
    op.add_column("global_config", sa.Column("max_tokens", sa.Integer(), nullable=True))
    op.add_column("global_config", sa.Column("stream", sa.Integer(), nullable=True))
    op.add_column("global_config", sa.Column("jailbreak_prefix", sa.Text(), nullable=True))
    op.add_column("global_config", sa.Column("system_template", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("global_config", "system_template")
    op.drop_column("global_config", "jailbreak_prefix")
    op.drop_column("global_config", "stream")
    op.drop_column("global_config", "max_tokens")
    op.drop_column("global_config", "top_p")
    op.drop_column("global_config", "temperature")
    # ### end Alembic commands ###
