"""add core_event to chapters

Revision ID: b5cff3371f1b
Revises: 5c26fcbf2d50
Create Date: 2026-03-10 19:04:00.316853

"""

from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b5cff3371f1b"
down_revision: str | None = "5c26fcbf2d50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chapters", sa.Column("core_event", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chapters", "core_event")
    # ### end Alembic commands ###
