"""add content field to Chapter

Revision ID: d2833dd427d4
Revises: b5cff3371f1b
Create Date: 2026-03-10 23:40:30.959658

"""

from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d2833dd427d4"
down_revision: str | None = "b5cff3371f1b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chapters", sa.Column("content", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chapters", "content")
    # ### end Alembic commands ###
